# port of HTTP
port: 7890

# port of SOCKS5
socks-port: 1080

# (HTTP and SOCKS5 in one port)
# mixed-port: 7890

# redir port for Linux and macOS
# redir-port: 7892

allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:

#########################
proxy-groups:
  - name: all
    type: load-balance
    use:
      - all
    url: "http://clients3.google.com/generate_204"
    interval: 300

proxy-providers:
  all:
    type: http
    url: "https://proxies.bihai.cf/clash/proxies?c=DE,GB,NL,FR&filter=nrp"
    # url: "https://raw.githubusercontent.com/mahdibland/SSAggregator/master/utils/speedtest/provider.yaml"
    path: bihai/no.yaml
    health-check:
      enable: true
      interval: 300
      url: http://clients3.google.com/generate_204

rules:
  - DOMAIN-SUFFIX,githubusercontent.com,DIRECT
  - DOMAIN-SUFFIX,github.com,DIRECT
  - MATCH,all
########################
